name: Compile Java

on:
  workflow_call: # Allows this workflow to be called from other repositories
    inputs:
      java_version:
        type: string
        default: 17
      java_flavour:
        type: string
        default: temurin
      build_command:
        type: string
        default: './mvnw compile'

jobs:
  compile_java:
    name: Compile Java
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_flavour }}
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ hashFiles('**/pom.xml') }}

      - name: Compile Code
        run: ${{ input.build_command }}
