name: Build Docker Image

on:
  workflow_call: # Allows this workflow to be called from other repositories
    inputs:
      app_name:
        type: string
        required: true
      tag:
        type: string
        default: latest
      dockerfile_location:
        type: string
        required: true

env:
  RUNNER_ROLE_ARN: arn:aws:iam::817667413626:role/GitHubRunner
  REGION: ap-southeast-1
  ECR_URI: 817667413626.dkr.ecr.ap-southeast-1.amazonaws.com/test

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download the JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: target

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ env.RUNNER_ROLE_ARN }}
#          role-session-name: github-runner
#          aws-region: ${{ env.REGION }}
#
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          platforms: linux/amd64
#          push: true
#          context: .
#          no-cache: true
#          tags: ${{ env.ECR_URI }}:${{ inputs.tag }}
