name: Code Scanning

on:
  workflow_call: # Allows this workflow to be called from other repositories
    inputs:
      language:
        type: string
        default: java
      language_version:
        type: string
        default: 17
      language_flavour:
        type: string
        default: temurin
      artifact_path:
        type: string
        required: true

jobs:
  code_analysis_java:
    name: CodeQL Scanning for Java
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: inputs.language == 'java'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.language_version }}
          distribution: ${{ inputs.language_flavour }}
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ hashFiles('**/pom.xml') }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ inputs.artifact_path }}/

      - name: Checkinng
        run: |
          pwd
          ls -lha
          cd target 
          ls -lha
          cd classes
          ls -lha

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  code_analysis_nodejs:
    name: CodeQL Scanning for Nodejs
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: inputs.language == 'nodejs'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.language_version }}
          cache: 'npm'

      - name: Cache local npm repository
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
