name: Code Scanning

on:
  workflow_call: # Allows this workflow to be called from other repositories
    inputs:
      language:
        type: string
        default: java
      language_version:
        type: string
        default: 17
      language_flavour:
        type: string
        default: temurin
      command:
        type: string
        required: true
      enable:
        type: string
        default: true

jobs:
  code_analysis_java:
    name: CodeQL Scanning for Java
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: inputs.language == 'java'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK
        if: inputs.enable == true
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.language_version }}
          distribution: ${{ inputs.language_flavour }}
          cache: 'maven'

      - name: Cache local Maven repository
        if: inputs.enable == true
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ hashFiles('**/pom.xml') }}

      - name: Initialize CodeQL
        if: inputs.enable == true
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Compile Code
        if: inputs.enable == true
        run: ${{ inputs.command }}

      - name: Perform CodeQL Analysis
        if: inputs.enable == true
        uses: github/codeql-action/analyze@v3

  code_analysis_nodejs:
    name: CodeQL Scanning for Nodejs
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: inputs.language == 'nodejs'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        if: inputs.enable == true
        with:
          node-version: ${{ inputs.language_version }}
          cache: 'npm'

      - name: Cache local npm repository
        if: inputs.enable == true
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - name: Initialize CodeQL
        if: inputs.enable == true
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        if: inputs.enable == true
        uses: github/codeql-action/analyze@v3
