name: Deploy App

on:
  workflow_call:
    inputs:
      tag:
        type: string
        default: "dev"
      app_name:
        type: string
        required: true
      namespace:
        type: string
        required: true
      helm_chart:
        type: string
        default: "generic"
      values_file_location:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Clone Deployment Repo
        run: |
          rm -rf deployments
          git clone https://git:${{ secrets.GH_TOKEN }}@github.com/phu-ng/deployments.git
      #          echo abc > abc.txt
      #          git config --global --add safe.directory $PWD
      #          git config user.name "github-bot"
      #          git config user.email "github-bot@users.noreply.github.com"
      #          git add .
      #          git commit -m "Update from GitHub Actions"
      #          git push origin main

      - name: Deploy with new value or image tag
        run: echo helm upgrade --install "${{ inputs.app_name }}" -f "${{ inputs.values_file_location }}" --set image.tag="${{ inputs.tag }}" --namespace "${{ inputs.namespace }}"
