name: Deploy App

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        default: "dev"
      appName:
        type: string
        required: true
      namespace:
        type: string
        required: true
      helmVersion:
        type: string
        default: "0.1.0"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Pull helm chart from ECR
        run: echo helm pull from ECR

      - name: Deploy with new value or image tag
        run: echo helm upgrade --install "${{ inputs.appName }}" -f ./deployments/dev/values.yaml --set image.tag="${{ inputs.imageTag }}" --version "${{ inputs.helmVersion }}" --namespace "${{ inputs.namespace }}"
