name: Deploy App

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      appName:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Pull helm chart from ECR
        run: echo helm pull from ECR

      - name: Deploy with new value or image tag
        run: echo helm upgrade --install " ${{ inputs.appName }} " -f ./deployments/dev/values.yaml