name: Java Maven Build

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

env:
  RUNNER_ROLE_ARN: arn:aws:iam::817667413626:role/GitHubRunner
  REGION: ap-southeast-1
  ECR_URI: 817667413626.dkr.ecr.ap-southeast-1.amazonaws.com/test

jobs:
  gather_information:
    name: Gather Information
    uses: phu-ng/cicd-scripts/.github/workflows/gather_information.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build_java:
    needs: gather_information
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: needs.gather_information.outputs.language == 'java'

    steps:
      - name: Running java
        run: echo this is java
