name: Java Maven Build

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

env:
  RUNNER_ROLE_ARN: arn:aws:iam::817667413626:role/GitHubRunner
  REGION: ap-southeast-1
  ECR_URI: 817667413626.dkr.ecr.ap-southeast-1.amazonaws.com/test

jobs:
  gather_information:
    name: Gather Information
    uses: phu-ng/cicd-scripts/.github/workflows/gather_information.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  check:
    needs: gather_information
    steps:
      - name: check
        run: echo "${{needs.gather_information.outputs.language }}"
    runs-on: ubuntu-22.04
    timeout-minutes: 10

#  build_java:
#    needs: gather_information
#    if: needs.gather_information.outputs.language == 'java'
#    uses: phu-ng/cicd-scripts/.github/workflows/build_java.yaml@main
#    with:
#      java_version: needs.gather_information.outputs.language_version
#      build_command: needs.gather_information.outputs.build_command
